title: Page
pages: true
files: true
fields:
  heroimage: heroimage
  imagefit: imagefit
  title: title
  author:
    label: Author
    type: text
    help: Firstname Lastname
  created:
    label: Created
    type: date
    required: false
  intro: intro
  text: text
  voucherform: voucherform
  border: border
