title: Page
pages: true
files: true
fields:
  heroimage: heroimage
  imagefit: imagefit
  title: title
  menu: menu
  author:
    label: Author
    type: text
    help: Firstname Lastname
  created:
    label: Created
    type: date
    required: false
  intro: intro
  text: text
  embed:
    label: Embed bottom
    type: textarea
    help: full width field for embedding something like Curator.io
